
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

dist: xenial

services:
  - mysql

addons:
  postgresql: "9.6"

matrix:
  include:
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv
  - if [ ! -z "$CORE_PATCH" ]; then (cd /home/travis/build/moodle; git am --whitespace=nowarn < admin/tool/objectfs/patch/$CORE_PATCH); fi

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
